pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    // Clone the repository
                    git url: 'https://github.com/4q78/pipelineTest', branch: 'main'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Compile your code
                    // Adjust the command if you are not using Java or have a different build process
                    sh 'javac pipeline.java'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Run your tests
                    // Ensure HelloWorld.class is generated by the build stage
                    sh 'java pipeline'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Deploy your application
                    // This is a placeholder; adjust as needed for your actual deployment process
                    echo 'Deploying application...'
                }
            }
        }
    }

    post {
        always {
            script {
                // Clean up after build
                echo 'Cleaning up...'
            }
        }
    }
}